[bem-renaming] Rename all the classes using standard BEM syntax
dreipol/vue-ui pull request #45
Opened 2021-02-18 13:16 UTC by GianlucaGuarini

As already discussed several times this PR standardizes the use of BEM in our components

2021-02-18 13:39 UTC, jessicachrist approved these changes
LGTM

2021-02-18 14:02 UTC, TBadoux requested changes

2021-02-18 14:46 UTC, GianlucaGuarini commented on src/components/accordion/README.md
>          &.ui-accordion__is-animating {
good point. Danke @TBadoux

2021-02-19 09:09 UTC, GianlucaGuarini commented
I am going to merge this PR and move forward

2021-02-19 09:10 UTC, merged